// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repeat;

#nullable disable

namespace lab_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215072132_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BaseMailItemTag", b =>
                {
                    b.Property<int>("MailItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MailItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BaseMailItemTag");
                });

            modelBuilder.Entity("Repeat.BaseMailItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Невідомий");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("MailItems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseMailItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Repeat.MailLog", b =>
                {
                    b.Property<int>("MailItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MailItemId", "LogDate");

                    b.ToTable("MailLogs");
                });

            modelBuilder.Entity("Repeat.ParcelMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ParcelId")
                        .IsUnique();

                    b.ToTable("ParcelMetadatas", t =>
                        {
                            t.HasCheckConstraint("CK_Weight_Positive", "Weight > 0");
                        });
                });

            modelBuilder.Entity("Repeat.PostOfficeBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Київ, вул. Хрещатик, 1"
                        });
                });

            modelBuilder.Entity("Repeat.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Терміново"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Крихке"
                        });
                });

            modelBuilder.Entity("Repeat.Letter", b =>
                {
                    b.HasBaseType("Repeat.BaseMailItem");

                    b.HasDiscriminator().HasValue("Letter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Name = "Лист",
                            ReceiverName = "Іван",
                            SenderName = "Петро"
                        });
                });

            modelBuilder.Entity("Repeat.Parcel", b =>
                {
                    b.HasBaseType("Repeat.BaseMailItem");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Parcel");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Name = "Посилка",
                            ReceiverName = "Марія",
                            SenderName = "Ольга",
                            TrackingNumber = "TRACK123"
                        });
                });

            modelBuilder.Entity("BaseMailItemTag", b =>
                {
                    b.HasOne("Repeat.BaseMailItem", null)
                        .WithMany()
                        .HasForeignKey("MailItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repeat.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repeat.BaseMailItem", b =>
                {
                    b.HasOne("Repeat.PostOfficeBranch", "Branch")
                        .WithMany("MailItems")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Repeat.ParcelMetadata", b =>
                {
                    b.HasOne("Repeat.Parcel", "Parcel")
                        .WithOne("Metadata")
                        .HasForeignKey("Repeat.ParcelMetadata", "ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("Repeat.PostOfficeBranch", b =>
                {
                    b.Navigation("MailItems");
                });

            modelBuilder.Entity("Repeat.Parcel", b =>
                {
                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
